### ISSUE TITLE
Failed to bootstrap path 

### ISSUE THREAD

**Issue by lovegu0713** [YBN-JUAN/X1C6-OpenCore-EFI#7]
直接使用会出现很多  Failed to bootstrap path 
机器配置如下：x1 carbon 2018    
CPU：i7 8550U 2.0GHz
显卡：UHD620 1536MB
内存：16GB LPDDR3 2133MHz
硬盘0：西数 SN550 NVMe SSD 1TB
硬盘1：西数 SN520 NVMe SSD512GB  安装到了wwan位置
屏幕：14“ 2560×1440

error：
![image](https://user-images.githubusercontent.com/16776079/107868797-2e093c00-6ec2-11eb-81c5-167085fa6bd8.png)

换了多个 版本HFSPlus.efi 还是一样，请问一下具体原因，谢谢

**Comment by YBN-JUAN** [comment]
OC新版本已经移除了Bootstrap，具体可以看下官方文档，跟HFSPlus没关系。config我可能更新得不是那么勤，所以有些字段没有及时跟上官方的sample。
